source=~/.config/dotfiles/hypr/variables.conf

WALLPAPER_DIR="~/.config/dotfiles/hypr/images/wallpapers"
wallpaper="~/.config/dotfiles/hypr/images/wallpapers/rain_road_tree_foggy_bush_flowers_girl_umbrela_grey_outside_mountain.jpg"

wallpaper {
  monitor = 
  path=~/.config/dotfiles/hypr/images/current/wallpaper.jpg
  fit_mode = fill
}

splash = false
