# source variables.conf

$pathToWallpaper = ~/.config/dotfiles/hypr/images/wallpapers/rain_road_tree_foggy_bush_flowers_girl_umbrela_grey_outside_mountain.jpg
wallpaper {
  monitor = 
  path = $pathToWallpaper
  fit_mode = fill
}
